CREATE TABLE IF NOT EXISTS users (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                     name VARCHAR(255) NOT NULL,
                                     email VARCHAR(512) NOT NULL,
                                     CONSTRAINT pk_user PRIMARY KEY (id),
                                     CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);
CREATE TABLE IF NOT EXISTS requests (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                     description VARCHAR(512) NOT NULL,
                                     requestor_id BIGINT NOT NULL,
                                     CONSTRAINT pk_request PRIMARY KEY (id),
                                     CONSTRAINT requestor_id_fk FOREIGN KEY (requestor_id) REFERENCES users(id)
);
CREATE TABLE IF NOT EXISTS items (
                                       id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY ,
                                       name VARCHAR(255) NOT NULL,
                                       description VARCHAR(512) NOT NULL,
                                       is_available BOOLEAN DEFAULT false,
                                       owner_id BIGINT NOT NULL ,
                                       request_id BIGINT NOT NULL ,
                                       CONSTRAINT item_pk PRIMARY KEY (id),
                                       CONSTRAINT owner_id_fk FOREIGN KEY (owner_id) REFERENCES users (id),
                                       CONSTRAINT requst_id_fk FOREIGN KEY (request_id) REFERENCES requests (id)
  );
CREATE TYPE booking_status AS ENUM ('waiting','approved','rejected','canceled')
;
CREATE TABLE IF NOT EXISTS bookings (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                     start_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                                     end_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                                     item_id  BIGINT NOT NULL,
                                     booker_id BIGINT NOT NULL,
                                     status booking_status NOT NULL DEFAULT 'waiting',
                                     CONSTRAINT pk_booking PRIMARY KEY (id),
                                     CONSTRAINT item_id_fk FOREIGN KEY (item_id) REFERENCES items(id),
                                     CONSTRAINT booker_id_fk FOREIGN KEY (booker_id) REFERENCES users(id)
);
CREATE TABLE IF NOT EXISTS comments(
                                        id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                        description VARCHAR(512) NOT NULL,
                                        item_id  BIGINT NOT NULL,
                                        author_id BIGINT NOT NULL,
                                        CONSTRAINT pk_comment PRIMARY KEY (id),
                                        CONSTRAINT item_comment_id_fk FOREIGN KEY (item_id) REFERENCES items(id),
                                        CONSTRAINT author_id_fk FOREIGN KEY (author_id) REFERENCES users(id)
);