CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255)                            NOT NULL,
    email VARCHAR(512)                            NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);
CREATE TABLE IF NOT EXISTS requests
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description  VARCHAR(512)                            NOT NULL,
    requestor_id BIGINT                                  NOT NULL,
    created      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_request PRIMARY KEY (id),
    CONSTRAINT requestor_id_fk FOREIGN KEY (requestor_id) REFERENCES users (id)
);
CREATE TABLE IF NOT EXISTS items
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         VARCHAR(255)                            NOT NULL,
    description  VARCHAR(512)                            NOT NULL,
    is_available BOOLEAN DEFAULT false,
    owner_id     BIGINT                                  NOT NULL,
    request_id   BIGINT,
    CONSTRAINT pk_item PRIMARY KEY (id),
    CONSTRAINT owner_id_fk FOREIGN KEY (owner_id) REFERENCES users (id),
    CONSTRAINT request_id_fk FOREIGN KEY (request_id) REFERENCES requests (id)
);

CREATE TABLE IF NOT EXISTS bookings
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    start_date TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    end_date   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    item_id    BIGINT                                  NOT NULL,
    booker_id  BIGINT                                  NOT NULL,
    status     VARCHAR(10)                             NOT NULL DEFAULT 'WAITING',
    CONSTRAINT pk_booking PRIMARY KEY (id),
    CONSTRAINT item_id_fk FOREIGN KEY (item_id) REFERENCES items (id),
    CONSTRAINT booker_id_fk FOREIGN KEY (booker_id) REFERENCES users (id)
);
CREATE TABLE IF NOT EXISTS comments
(
    id        BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    text      VARCHAR(512)                NOT NULL,
    item_id   BIGINT                      NOT NULL,
    author_id BIGINT                      NOT NULL,
    created   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT item_comment_id_fk FOREIGN KEY (item_id) REFERENCES items (id),
    CONSTRAINT author_fk FOREIGN KEY (author_id) REFERENCES users (id)
);

ALTER TABLE users
    ALTER COLUMN id RESTART WITH 1;
ALTER TABLE requests
    ALTER COLUMN id RESTART WITH 1;
ALTER TABLE items
    ALTER COLUMN id RESTART WITH 1;
ALTER TABLE bookings
    ALTER COLUMN id RESTART WITH 1;
ALTER TABLE comments
    ALTER COLUMN id RESTART WITH 1;

DELETE
FROM comments;
DELETE
FROM bookings;
DELETE
FROM items;
DELETE
FROM requests;
DELETE
FROM users;

